# Core cluster module - defines base options for all clusters
{ lib, config, ... }:

let
  # CLI command type
  commandType = lib.types.submodule {
    options = {
      description = lib.mkOption {
        type = lib.types.str;
        description = "Short description of the command";
      };

      builder = lib.mkOption {
        type = lib.types.functionTo lib.types.package;
        description = "Function that builds the command. Receives { pkgs, lib, cluster }";
      };
    };
  };

  # Member submodule - nixosConfiguration + patches + install options
  memberModule = lib.types.submodule ({ name, config, ... }: {
    # Freeform allows any NixOS options as patches
    freeformType = lib.types.attrsOf lib.types.anything;

    options = {
      nixosConfiguration = lib.mkOption {
        type = lib.types.raw;
        description = "Base NixOS configuration to extend";
      };

      install = lib.mkOption {
        type = lib.types.submodule {
          freeformType = lib.types.attrsOf lib.types.anything;
          options = {
            ip = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "IP address for deployment";
            };
          };
        };
        default = {};
        description = "Installation/deployment options";
      };
    };
  });

in
{
  options = {
    name = lib.mkOption {
      type = lib.types.str;
      description = "Cluster name";
    };

    members = lib.mkOption {
      type = lib.types.attrsOf memberModule;
      default = {};
      description = "Cluster members";
    };

    commands = lib.mkOption {
      type = lib.types.listOf (lib.types.attrsOf commandType);
      default = [];
      description = "CLI commands for nixclusterctl";
    };

    # Internal: NixOS modules generated by extensions (per member)
    _generatedNixosModules = lib.mkOption {
      type = lib.types.attrsOf (lib.types.listOf lib.types.deferredModule);
      default = {};
      internal = true;
      description = "NixOS modules generated by extensions";
    };
  };
}
