# SOPS cluster extension module
# Adds sops options and generates NixOS modules for secret management
{ lib, config, ... }:

let
  cfg = config.sops;
  clusterName = config.name;

  # Derived paths from secretsDir
  secretsFile = "${cfg.secretsDir}/${clusterName}.yaml";
  ageKeyFile = "${cfg.secretsDir}/${clusterName}.age.key";
  agePubFile = "${cfg.secretsDir}/${clusterName}.age.pub";
  sopsConfigFile = "${cfg.secretsDir}/.sops.yaml";

  # Generate NixOS module for sops-enabled members
  mkSopsNixosModule = memberName: member:
    { config, pkgs, ... }: {
      sops = {
        defaultSopsFile = secretsFile;
        age.keyFile = cfg.ageKeyFileOnHost;
        age.generateKey = false;
      };
    };

in
{
  options.sops = {
    enable = lib.mkEnableOption "SOPS secrets management";

    secretsDir = lib.mkOption {
      type = lib.types.str;
      default = "secrets";
      description = "Directory for SOPS secrets files (relative to project root)";
    };

    ageKeyFileOnHost = lib.mkOption {
      type = lib.types.str;
      default = "/etc/age/key.txt";
      description = "Path to the age private key on target systems";
    };
  };

  config = lib.mkIf cfg.enable {
    # Generate NixOS modules for all members
    _generatedNixosModules = lib.mapAttrs
      (name: member: [ (mkSopsNixosModule name member) ])
      config.members;

    # CLI commands for sops management
    commands = [{
      gen-secrets = {
        description = "Generate cluster secrets";
        builder = { pkgs, cluster, ... }:
          pkgs.writeShellApplication {
            name = "nix8sctl-${clusterName}-gen-secrets";
            runtimeInputs = with pkgs; [ coreutils openssh age sops ];
            text = ''
              set -euo pipefail

              FORCE="''${1:-}"

              SECRETS_DIR="${cfg.secretsDir}"
              AGE_KEY_FILE="${ageKeyFile}"
              AGE_PUB_FILE="${agePubFile}"
              SECRETS_FILE="${secretsFile}"
              SOPS_CONFIG="${sopsConfigFile}"

              mkdir -p "$SECRETS_DIR"

              # Check for existing files
              if [[ -f "$AGE_KEY_FILE" && "$FORCE" != "--force" ]]; then
                echo "Warning: Secrets already exist for cluster '${clusterName}'!"
                echo "Files: $AGE_KEY_FILE, $SECRETS_FILE"
                read -r -p "Overwrite all? [y/N] " response
                if [[ ! "$response" =~ ^[Yy]$ ]]; then
                  echo "Aborted."
                  exit 1
                fi
              fi

              echo "Generating secrets for cluster '${clusterName}'..."
              echo ""

              # 1. Generate age keypair
              echo "[1/4] Generating age keypair..."
              rm -f "$AGE_KEY_FILE" "$AGE_PUB_FILE"
              age-keygen 2>&1 | tee "$AGE_KEY_FILE.tmp"
              grep "AGE-SECRET-KEY-" "$AGE_KEY_FILE.tmp" > "$AGE_KEY_FILE"
              grep "public key:" "$AGE_KEY_FILE.tmp" | cut -d: -f2 | tr -d ' ' > "$AGE_PUB_FILE"
              rm "$AGE_KEY_FILE.tmp"
              chmod 600 "$AGE_KEY_FILE"
              AGE_PUB_KEY=$(cat "$AGE_PUB_FILE")
              echo "       Age public key: $AGE_PUB_KEY"

              # 2. Generate k3s tokens
              echo "[2/4] Generating k3s tokens..."
              TOKEN=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48)
              AGENT_TOKEN=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48)
              echo "       Generated 2 tokens"

              # 3. Create/update .sops.yaml configuration
              echo "[3/4] Creating .sops.yaml..."
              cat > "$SOPS_CONFIG" << EOF
            # SOPS configuration for nix8s secrets
            # Auto-generated by: nix8sctl ${clusterName} gen-secrets

            keys:
              - &${clusterName} $AGE_PUB_KEY

            creation_rules:
              - path_regex: ${clusterName}\\.yaml$
                key_groups:
                  - age:
                      - *${clusterName}
            EOF

              # 4. Create and encrypt secrets
              echo "[4/4] Creating and encrypting secrets..."
              PLAIN_FILE=$(mktemp)
              cat > "$PLAIN_FILE" << EOF
            # Cluster secrets for ${clusterName}
            # Edit with: nix8sctl ${clusterName} edit-secrets

            k3s:
              token: $TOKEN
              agentToken: $AGENT_TOKEN
            EOF

              export SOPS_AGE_KEY_FILE="$AGE_KEY_FILE"
              ENCRYPTED_FILE=$(mktemp)
              sops --config "$SOPS_CONFIG" --filename-override "$SECRETS_FILE" --encrypt "$PLAIN_FILE" > "$ENCRYPTED_FILE"
              mv "$ENCRYPTED_FILE" "$SECRETS_FILE"
              rm "$PLAIN_FILE"

              echo ""
              echo "=========================================="
              echo "Secrets generated successfully!"
              echo "=========================================="
              echo ""
              echo "Created files:"
              echo "  $AGE_KEY_FILE  - age private key (NEVER COMMIT)"
              echo "  $AGE_PUB_FILE  - age public key"
              echo "  $SECRETS_FILE  - encrypted secrets (safe to commit)"
              echo "  $SOPS_CONFIG   - sops configuration"
              echo ""
              echo "Next steps:"
              echo "  1. Add to .gitignore: $AGE_KEY_FILE"
              echo "  2. Commit: git add $AGE_PUB_FILE $SECRETS_FILE $SOPS_CONFIG"
            '';
          };
      };

      edit-secrets = {
        description = "Edit cluster secrets";
        builder = { pkgs, cluster, ... }:
          pkgs.writeShellApplication {
            name = "nix8sctl-${clusterName}-edit-secrets";
            runtimeInputs = with pkgs; [ sops ];
            text = ''
              SECRETS_FILE="${secretsFile}"
              AGE_KEY_FILE="${ageKeyFile}"
              SOPS_CONFIG="${sopsConfigFile}"

              if [[ ! -f "$SECRETS_FILE" ]]; then
                echo "Secrets file not found: $SECRETS_FILE"
                echo "Use 'gen-secrets' to create."
                exit 1
              fi

              export SOPS_AGE_KEY_FILE="$AGE_KEY_FILE"
              exec sops --config "$SOPS_CONFIG" "$SECRETS_FILE"
            '';
          };
      };

      show-secrets = {
        description = "Show decrypted secrets";
        builder = { pkgs, cluster, ... }:
          pkgs.writeShellApplication {
            name = "nix8sctl-${clusterName}-show-secrets";
            runtimeInputs = with pkgs; [ sops ];
            text = ''
              SECRETS_FILE="${secretsFile}"
              AGE_KEY_FILE="${ageKeyFile}"
              SOPS_CONFIG="${sopsConfigFile}"

              if [[ ! -f "$SECRETS_FILE" ]]; then
                echo "Secrets file not found: $SECRETS_FILE"
                exit 1
              fi

              export SOPS_AGE_KEY_FILE="$AGE_KEY_FILE"
              sops --config "$SOPS_CONFIG" --decrypt "$SECRETS_FILE"
            '';
          };
      };
    }];
  };
}
