# clusterOutputs - derive nixosConfigurations + CLI from an evaluated cluster
# config. Shared by mkCluster (standalone API) and the flake-parts module so
# both produce identical outputs from the same evaluated `cfg`.
{ lib }:

let
  mkClusterCli = import ./mkClusterCli.nix { inherit lib; };
  resolveMemberBase = import ./resolveMemberBase.nix { inherit lib; };
  convergePlan = import ./convergePlan.nix { inherit lib; };

  # Keys that are nixcluster-specific, not NixOS patches.
  nixclusterKeys = [ "nixosConfiguration" "install" ];
in

cfg:

let
  # Build the final NixOS configuration for each member.
  mkMemberNixosConfig = memberName: member:
    let
      # Everything except nixcluster-specific keys is a NixOS patch.
      nixosPatches = removeAttrs member nixclusterKeys;

      # Modules generated by extensions (k3s, sops, incus, ...).
      extensionModules = cfg._generatedNixosModules.${memberName} or [];

      # Cluster context for NixOS modules (the `nixcluster` module arg).
      clusterContext = {
        _module.args.nixcluster = {
          cluster = cfg;
          clusterName = cfg.name;
          inherit memberName member;
        };
      };

      # Effective base config: member's own, else cluster default (throws if none).
      baseNixosConfiguration = resolveMemberBase cfg memberName member;
    in
    baseNixosConfiguration.extendModules {
      modules = [
        nixosPatches
        clusterContext
      ] ++ extensionModules;
    };
in
{
  nixosConfigurations = lib.mapAttrs mkMemberNixosConfig cfg.members;

  # Resolved converge execution order (topological over `converge.steps`).
  # Exposed so downstream flakes and template checks can assert the ordering
  # contract without building the CLI.
  convergeOrder = convergePlan cfg;

  # CLI subcommand builder: pkgs -> package
  cli = pkgs: mkClusterCli { inherit pkgs; cluster = cfg; };
}
