# mkClusterCli - Build CLI subcommand for a cluster
#
# Two-level router:
#   nixclusterctl <cluster> <command> [args...]            (top-level core command)
#   nixclusterctl <cluster> <group> <action> [args...]     (namespaced module command)
#
# Top-level commands come from `cluster.commands` (core: apply/install/gen-config).
# Module commands come from `cluster.commandGroups.<group>.actions.<action>`.
# Everything after the resolved command/action is passed through verbatim, so a
# `--` passthrough boundary (e.g. `incus exec web -- bash`) reaches the node tool
# untouched by our router.
{ lib }:

{ pkgs, cluster }:

let
  clusterName = cluster.name;
  memberNames = lib.attrNames cluster.members;

  # Shared table renderer: reads TSV on stdin, prints aligned columns.
  # Commands emit tab-separated rows and pipe through this for human output;
  # the same data backs `--json` where a command implements it.
  tablefmt = pkgs.writeShellApplication {
    name = "tablefmt";
    runtimeInputs = [ pkgs.util-linux ];
    text = ''
      exec column -t -s "$(printf '\t')"
    '';
  };

  helpers = { inherit tablefmt; };

  # Base (core) top-level commands, always available.
  baseCommands = {
    apply = {
      description = "Apply config to member";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-apply";
          runtimeInputs = with pkgs; [ nixos-rebuild openssh ];
          text = ''
            MEMBER="''${1:-}"
            IP="''${2:-}"

            if [[ -z "$MEMBER" ]]; then
              echo "Usage: nixclusterctl ${clusterName} apply <member> [ip]"
              echo "Members: ${lib.concatStringsSep ", " memberNames}"
              exit 1
            fi

            # Get IP from config or argument
            case "$MEMBER" in
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: member: ''
                ${name}) IP="''${IP:-${member.install.ip or ""}}" ;;
              '') cluster.members)}
            esac

            if [[ -z "$IP" ]]; then
              echo "Error: No IP for $MEMBER. Specify as argument."
              exit 1
            fi

            echo "Deploying ${clusterName}-$MEMBER to $IP..."
            nixos-rebuild switch \
              --flake ".#${clusterName}-$MEMBER" \
              --target-host "root@$IP"
          '';
        };
    };

    # gen-config (task 03): SSH-discover a node and emit a member module.
    gen-config = {
      description = "Discover a node over SSH and emit a member module";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-gen-config";
          runtimeInputs = with pkgs; [ openssh coreutils ];
          text = ''
            set -euo pipefail

            IP=""
            NAME=""
            SSH_USER="root"
            while [[ $# -gt 0 ]]; do
              case "$1" in
                --name) NAME="''${2:-}"; shift 2 ;;
                --ssh-user) SSH_USER="''${2:-}"; shift 2 ;;
                --*) echo "Unknown flag: $1" >&2; exit 1 ;;
                *)
                  if [[ -z "$IP" ]]; then IP="$1"; shift;
                  else echo "Unexpected argument: $1" >&2; exit 1; fi
                  ;;
              esac
            done

            if [[ -z "$IP" ]]; then
              echo "Usage: nixclusterctl ${clusterName} gen-config <ip> [--name <node-name>] [--ssh-user <user>]" >&2
              exit 1
            fi

            echo "Discovering node at $IP (user $SSH_USER)..." >&2

            # Bootstrap TOFU: accept-new pins on first contact, never disables checking (B3).
            SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)

            REMOTE_HOSTNAME=$(ssh "''${SSH_OPTS[@]}" "$SSH_USER@$IP" 'hostname' | tr -d "\r" | head -n1)

            # Pick the whole disk backing /, else the first disk. Reads the real
            # device from the node (e.g. /dev/vda on Colima), never hardcoded.
            DISK=$(ssh "''${SSH_OPTS[@]}" "$SSH_USER@$IP" 'set -e; root_src=$(findmnt -n -o SOURCE / 2>/dev/null || true); pk=""; if [ -n "$root_src" ]; then pk=$(lsblk -no PKNAME "$root_src" 2>/dev/null | head -n1); fi; if [ -n "$pk" ]; then echo "/dev/$pk"; else d=$(lsblk -dn -o NAME,TYPE | grep "disk$" | head -n1 | sed "s/[[:space:]].*//"); echo "/dev/$d"; fi' | tr -d "\r" | head -n1)

            NODE_NAME="''${NAME:-$REMOTE_HOSTNAME}"

            echo "  hostname: $REMOTE_HOSTNAME" >&2
            echo "  disk:     $DISK" >&2
            echo "  member:   $NODE_NAME" >&2

            printf '%s\n' \
              "# Generated by: nixclusterctl ${clusterName} gen-config $IP" \
              "# Save into modules/nodes/$NODE_NAME.nix" \
              "{ ... }:" \
              "{" \
              "  nixcluster.${clusterName}.members.$NODE_NAME = {" \
              "    # nixosConfiguration = ...;  # set your base NixOS config" \
              "    install.ip = \"$IP\";" \
              "    install.disk = \"$DISK\";" \
              "  };" \
              "}"
          '';
        };
    };

    # install (task 04): first-time provisioning via nixos-anywhere.
    install = {
      description = "Install a member via nixos-anywhere";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-install";
          runtimeInputs = with pkgs; [ nixos-anywhere openssh coreutils ];
          text = ''
            set -euo pipefail

            MEMBER=""
            IP=""
            AGE_KEY_FILE=""
            EXTRA_FILES=""
            while [[ $# -gt 0 ]]; do
              case "$1" in
                --age-key-file) AGE_KEY_FILE="''${2:-}"; shift 2 ;;
                --extra-files) EXTRA_FILES="''${2:-}"; shift 2 ;;
                --*) echo "Unknown flag: $1" >&2; exit 1 ;;
                *)
                  if [[ -z "$MEMBER" ]]; then MEMBER="$1";
                  elif [[ -z "$IP" ]]; then IP="$1";
                  else echo "Unexpected argument: $1" >&2; exit 1; fi
                  shift
                  ;;
              esac
            done

            if [[ -z "$MEMBER" ]]; then
              echo "Usage: nixclusterctl ${clusterName} install <member> [ip] [--age-key-file <path>] [--extra-files <dir>]" >&2
              echo "Members: ${lib.concatStringsSep ", " memberNames}" >&2
              exit 1
            fi

            # Default IP from member config.
            case "$MEMBER" in
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: member: ''
                ${name}) IP="''${IP:-${member.install.ip or ""}}" ;;
              '') cluster.members)}
            esac

            if [[ -z "$IP" ]]; then
              echo "Error: no IP for $MEMBER (set members.$MEMBER.install.ip or pass as arg)" >&2
              exit 1
            fi

            STAGED=""
            cleanup() { [[ -n "$STAGED" ]] && rm -rf "$STAGED"; }
            trap cleanup EXIT

            EF_ARGS=()
            if [[ -n "$AGE_KEY_FILE" ]]; then
              # I3: deliver the age private key into the node's real filesystem at
              # /etc/age/key.txt (mode 0600), outside the nix store/closure. sops-nix
              # reads it on activation (sops.ageKeyFileOnHost), never via the store.
              STAGED=$(mktemp -d)
              install -m 600 -D "$AGE_KEY_FILE" "$STAGED/etc/age/key.txt"
              EF_ARGS+=(--extra-files "$STAGED")
            elif [[ -n "$EXTRA_FILES" ]]; then
              EF_ARGS+=(--extra-files "$EXTRA_FILES")
            fi

            echo "Installing ${clusterName}-$MEMBER on $IP via nixos-anywhere..." >&2
            nixos-anywhere \
              --flake ".#${clusterName}-$MEMBER" \
              --target-host "root@$IP" \
              "''${EF_ARGS[@]}"

            # B3: pin the node host key for subsequent runtime ssh (no accept-new later).
            KH_DIR="./.nixcluster/known_hosts"
            mkdir -p "$KH_DIR"
            ssh-keyscan -H "$IP" >> "$KH_DIR/${clusterName}" 2>/dev/null || true
            echo "Pinned host key for $IP in $KH_DIR/${clusterName}" >&2
          '';
        };
    };
    # converge (task E): orchestrate a whole cluster in one shot — run
    # cluster-level preSteps, install/switch every member (bootstrap first,
    # install-once vs switch decided by an SSH probe), run postSteps, then emit
    # a single machine-readable result line. Reuses the install/apply member->IP
    # `case`, the `.#<cluster>-<member>` flake attr, and the known_hosts pin;
    # step logic is reused from the modules (never reimplemented here).
    converge = {
      description = "Converge the whole cluster (preSteps -> per-member install/switch -> postSteps)";
      builder = { pkgs, lib, cluster, helpers, ... }:
        let
          # Deterministic member order: bootstrapMember (if set) leads, the rest
          # follow the explicit `order` (if set) or sorted-by-name.
          sortedMembers = lib.sort (a: b: a < b) memberNames;
          explicitOrder = cluster.converge.order or [];
          bootstrapMember = cluster.converge.bootstrapMember or null;
          baseOrder = if explicitOrder != [] then explicitOrder else sortedMembers;
          convergeOrder =
            if bootstrapMember != null
            then [ bootstrapMember ] ++ (lib.filter (m: m != bootstrapMember) baseOrder)
            else baseOrder;

          # Steps ordered by priority then name (deterministic; §4, minimal).
          sortSteps = steps:
            lib.sort
              (a: b: if a.priority != b.priority then a.priority < b.priority else a.name < b.name)
              (lib.mapAttrsToList (name: s: s // { inherit name; }) steps);

          preStepsSorted = sortSteps (cluster.converge.preSteps or {});
          postStepsSorted = sortSteps (cluster.converge.postSteps or {});

          # Build each step's package once and emit a `run_step` invocation.
          mkStepRuns = phase: steps: lib.concatMapStringsSep "\n" (s:
            ''run_step ${lib.escapeShellArg s.name} ${lib.escapeShellArg phase} ${lib.escapeShellArg (lib.getExe (s.run { inherit pkgs lib cluster helpers; }))}''
          ) steps;

          # member -> default install.ip, reusing the install/apply case shape.
          memberIpCases = lib.concatStringsSep "\n              " (lib.mapAttrsToList
            (name: member: ''${name}) echo "${member.install.ip or ""}" ;;'')
            cluster.members);

          orderArray = lib.concatStringsSep " " (map lib.escapeShellArg convergeOrder);
        in
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-converge";
          runtimeInputs = with pkgs; [ nixos-anywhere nixos-rebuild openssh jq coreutils ];
          text = ''
            set -euo pipefail

            JSON=0
            DRY_RUN=0
            AGE_KEY_FILE=""
            EXTRA_FILES=""
            while [[ $# -gt 0 ]]; do
              case "$1" in
                --json) JSON=1; shift ;;
                --dry-run) DRY_RUN=1; shift ;;
                --age-key-file) AGE_KEY_FILE="''${2:-}"; shift 2 ;;
                --extra-files) EXTRA_FILES="''${2:-}"; shift 2 ;;
                -h|--help)
                  echo "Usage: nixclusterctl ${clusterName} converge [--json] [--dry-run] [--age-key-file <path>] [--extra-files <dir>]" >&2
                  exit 0 ;;
                *) echo "Unknown flag: $1" >&2; exit 1 ;;
              esac
            done

            # All human output goes to stderr; stdout carries ONLY the result
            # line so `--json` yields a bare object and greppers get one marker.
            log() { echo "$@" >&2; }

            # --- accumulators (built with jq; never hand-concatenated) ---------
            MEMBERS_JSON='[]'
            STEPS_JSON='[]'

            add_member() { # name ip action status message durationSeconds
              MEMBERS_JSON=$(jq -c \
                --arg name "$1" --arg ip "$2" --arg action "$3" \
                --arg status "$4" --arg message "$5" --argjson dur "$6" \
                '. += [{name:$name,ip:$ip,action:$action,status:$status,message:$message,durationSeconds:$dur}]' \
                <<<"$MEMBERS_JSON")
            }
            add_step() { # name phase status message
              STEPS_JSON=$(jq -c \
                --arg name "$1" --arg phase "$2" --arg status "$3" --arg message "$4" \
                '. += [{name:$name,phase:$phase,status:$status,message:$message}]' \
                <<<"$STEPS_JSON")
            }

            # --- known_hosts pin (B3), shared with install --------------------
            KH_DIR="./.nixcluster/known_hosts"
            KH_FILE="$KH_DIR/${clusterName}"
            mkdir -p "$KH_DIR"; touch "$KH_FILE"
            SSH_OPTS=(-o UserKnownHostsFile="$KH_FILE" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)

            member_ip() {
              case "$1" in
              ${memberIpCases}
                *) echo "" ;;
              esac
            }

            # --extra-files staging mirrors `install`: the age private key lands
            # at /etc/age/key.txt (0600) on the node, outside the nix store.
            STAGED=""
            cleanup() { [[ -n "$STAGED" ]] && rm -rf "$STAGED"; return 0; }
            trap cleanup EXIT
            EF_ARGS=()
            if [[ -n "$AGE_KEY_FILE" ]]; then
              STAGED=$(mktemp -d)
              install -m 600 -D "$AGE_KEY_FILE" "$STAGED/etc/age/key.txt"
              EF_ARGS+=(--extra-files "$STAGED")
            elif [[ -n "$EXTRA_FILES" ]]; then
              EF_ARGS+=(--extra-files "$EXTRA_FILES")
            fi

            run_step() { # name phase exe
              local name="$1" phase="$2" exe="$3"
              if [[ "$DRY_RUN" -eq 1 ]]; then
                log "  [step:$phase] $name (dry-run, not executed)"
                add_step "$name" "$phase" skipped "dry-run"
                return 0
              fi
              log "=== step [$phase] $name ==="
              if "$exe"; then
                add_step "$name" "$phase" ok ""
              else
                add_step "$name" "$phase" failed "step exited non-zero"
              fi
            }

            converge_member() { # member
              local member="$1" ip probe start end
              ip="$(member_ip "$member")"
              if [[ "$DRY_RUN" -eq 1 ]]; then
                log "  [member] $member -> ''${ip:-<no-ip>} (dry-run, not probed)"
                add_member "$member" "$ip" noop Skipped "dry-run" 0
                return 0
              fi
              if [[ -z "$ip" ]]; then
                log "  [member] $member has no install.ip; skipping"
                add_member "$member" "" noop Failed "no install.ip for $member" 0
                return 0
              fi
              start=$(date +%s)
              probe=$(ssh "''${SSH_OPTS[@]}" "root@$ip" \
                'test -e /run/current-system && echo INSTALLED || echo FRESH' 2>/dev/null \
                || echo UNREACHABLE)
              case "$probe" in
                INSTALLED)
                  log "=== switch $member ($ip) [nixos-rebuild] ==="
                  if nixos-rebuild switch --flake ".#${clusterName}-$member" --target-host "root@$ip"; then
                    end=$(date +%s); add_member "$member" "$ip" switch Applied "" $((end - start))
                  else
                    end=$(date +%s); add_member "$member" "$ip" switch Failed "nixos-rebuild switch failed" $((end - start))
                  fi
                  ;;
                FRESH)
                  log "=== install $member ($ip) [nixos-anywhere] ==="
                  if nixos-anywhere --flake ".#${clusterName}-$member" --target-host "root@$ip" "''${EF_ARGS[@]}"; then
                    end=$(date +%s); add_member "$member" "$ip" install Applied "" $((end - start))
                    ssh-keyscan -H "$ip" >> "$KH_FILE" 2>/dev/null || true
                  else
                    end=$(date +%s); add_member "$member" "$ip" install Failed "nixos-anywhere failed" $((end - start))
                  fi
                  ;;
                *)
                  end=$(date +%s); add_member "$member" "$ip" noop Failed "unreachable ($probe)" $((end - start))
                  ;;
              esac
            }

            log "Converging cluster '${clusterName}'"
            log "Member order: ${lib.concatStringsSep " " convergeOrder}"
            log ""

            # 1) preSteps
            log "--- preSteps ---"
            ${mkStepRuns "pre" preStepsSorted}

            # 2) per-member install/switch loop
            log "--- members ---"
            ORDER=(${orderArray})
            for m in "''${ORDER[@]}"; do
              converge_member "$m"
            done

            # 3) postSteps
            log "--- postSteps ---"
            ${mkStepRuns "post" postStepsSorted}

            # 4) result + emit
            RESULT=$(jq -rn --argjson m "$MEMBERS_JSON" --argjson s "$STEPS_JSON" '
              if ($m | any(.status=="Failed")) or ($s | any(.status=="failed")) then "failed"
              elif ($m | any(.status=="Skipped")) or ($s | any(.status=="skipped")) then "partial"
              else "success" end')
            FINAL=$(jq -n -c \
              --arg cluster "${clusterName}" --arg result "$RESULT" \
              --argjson members "$MEMBERS_JSON" --argjson steps "$STEPS_JSON" \
              '{cluster:$cluster,result:$result,members:$members,steps:$steps}')

            log ""
            if [[ "$JSON" -eq 1 ]]; then
              printf '%s\n' "$FINAL"
            else
              printf '::nixcluster:result:: %s\n' "$FINAL"
            fi
          '';
        };
    };
  };

  # Top-level commands = base + any contributed via cluster.commands (attrsOf).
  topCommands = lib.mapAttrs (cmdName: cmdDef: {
    inherit (cmdDef) description;
    package = cmdDef.builder { inherit pkgs lib cluster helpers; };
  }) (baseCommands // (cluster.commands or {}));

  # Namespaced groups, each with built action packages.
  groups = lib.mapAttrs (groupName: groupDef: {
    inherit (groupDef) description;
    actions = lib.mapAttrs (actionName: actionDef: {
      inherit (actionDef) description;
      package = actionDef.builder { inherit pkgs lib cluster helpers; };
    }) groupDef.actions;
  }) (cluster.commandGroups or {});

  # --- help text -------------------------------------------------------------
  topHelp = lib.concatStringsSep "\n"
    (lib.mapAttrsToList (n: c: "  ${n} - ${c.description}") topCommands);

  groupHelp = lib.concatStringsSep "\n" (lib.mapAttrsToList (gName: g:
    let actions = lib.concatStringsSep ", " (lib.attrNames g.actions);
    in "  ${gName} - ${g.description} (${actions})"
  ) groups);

  # --- router cases ----------------------------------------------------------
  topCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (name: cmd: ''
    ${name})
      shift
      exec ${lib.getExe cmd.package} "$@"
      ;;
  '') topCommands);

  groupCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (gName: g:
    let
      actionCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (aName: a: ''
        ${aName})
          shift
          exec ${lib.getExe a.package} "$@"
          ;;
      '') g.actions);
      actionList = lib.concatStringsSep ", " (lib.attrNames g.actions);
    in ''
    ${gName})
      shift
      ACTION="''${1:-}"
      case "$ACTION" in
      ${actionCases}
        help|--help|-h|"")
          echo "${gName} - ${g.description}"
          echo "Actions: ${actionList}"
          ;;
        *) echo "Unknown ${gName} action: $ACTION"; echo "Actions: ${actionList}"; exit 1 ;;
      esac
      ;;
  '') groups);

in
pkgs.writeShellApplication {
  name = "nixclusterctl-${clusterName}";
  text = ''
    show_help() {
      cat << 'EOF'
    nixclusterctl ${clusterName}

    Commands:
    ${topHelp}

    Command groups:
    ${groupHelp}

    Members: ${lib.concatStringsSep ", " memberNames}
    EOF
    }

    CMD="''${1:-}"
    case "$CMD" in
    ${topCases}
    ${groupCases}
      help|--help|-h|"") show_help ;;
      *) echo "Unknown: $CMD"; show_help; exit 1 ;;
    esac
  '';
}
