# mkCluster - Evaluate a cluster configuration
#
# Usage:
#   nix8s.lib.mkCluster {
#     imports = [ nix8s.clusterModules.k3s ];
#     members.node1 = {
#       nixosConfiguration = self.nixosConfigurations.base;
#       install.ip = "10.0.0.1";
#       networking.hostName = "prod-node1";  # NixOS patch
#     };
#   }
{ lib, inputs }:

clusterConfig:

let
  # Import CLI builder
  mkClusterCli = import ./mkClusterCli.nix { inherit lib; };

  # Core cluster module
  coreModule = ../cluster-modules/core.nix;

  # Evaluate the cluster using module system
  evaluated = lib.evalModules {
    modules = [
      coreModule
      clusterConfig
    ];
  };

  cfg = evaluated.config;

  # Keys that are nix8s-specific, not NixOS patches
  nix8sKeys = [ "nixosConfiguration" "install" ];

  # Build final NixOS configuration for each member
  mkMemberNixosConfig = memberName: member:
    let
      # Extract NixOS patches (everything except nix8s keys)
      nixosPatches = removeAttrs member nix8sKeys;

      # Modules generated by extensions (k3s, etc)
      extensionModules = cfg._generatedNixosModules.${memberName} or [];

      # Cluster context for NixOS modules
      clusterContext = {
        _module.args.nix8s = {
          cluster = cfg;
          clusterName = cfg.name;
          inherit memberName member;
        };
      };
    in
    member.nixosConfiguration.extendModules {
      modules = [
        nixosPatches
        clusterContext
      ] ++ extensionModules;
    };

  nixosConfigurations = lib.mapAttrs mkMemberNixosConfig cfg.members;

  # CLI subcommand builder: pkgs -> package
  cli = pkgs: mkClusterCli { inherit pkgs; cluster = cfg; };

in
{
  inherit (evaluated) config options;
  inherit nixosConfigurations cli;
}
