# mkClusterCli - Build CLI subcommand for a cluster
#
# Two-level router:
#   nixclusterctl <cluster> <command> [args...]            (top-level core command)
#   nixclusterctl <cluster> <group> <action> [args...]     (namespaced module command)
#
# Top-level commands come from `cluster.commands` (core: apply/install/gen-config).
# Module commands come from `cluster.commandGroups.<group>.actions.<action>`.
# Everything after the resolved command/action is passed through verbatim, so a
# `--` passthrough boundary (e.g. `incus exec web -- bash`) reaches the node tool
# untouched by our router.
{ lib }:

{ pkgs, cluster }:

let
  clusterName = cluster.name;
  memberNames = lib.attrNames cluster.members;

  # Shared table renderer: reads TSV on stdin, prints aligned columns.
  # Commands emit tab-separated rows and pipe through this for human output;
  # the same data backs `--json` where a command implements it.
  tablefmt = pkgs.writeShellApplication {
    name = "tablefmt";
    runtimeInputs = [ pkgs.util-linux ];
    text = ''
      exec column -t -s "$(printf '\t')"
    '';
  };

  helpers = { inherit tablefmt; };

  # Base (core) top-level commands, always available.
  baseCommands = {
    apply = {
      description = "Apply config to member";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-apply";
          runtimeInputs = with pkgs; [ nixos-rebuild openssh ];
          text = ''
            MEMBER="''${1:-}"
            IP="''${2:-}"

            if [[ -z "$MEMBER" ]]; then
              echo "Usage: nixclusterctl ${clusterName} apply <member> [ip]"
              echo "Members: ${lib.concatStringsSep ", " memberNames}"
              exit 1
            fi

            # Get IP from config or argument
            case "$MEMBER" in
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: member: ''
                ${name}) IP="''${IP:-${member.install.ip or ""}}" ;;
              '') cluster.members)}
            esac

            if [[ -z "$IP" ]]; then
              echo "Error: No IP for $MEMBER. Specify as argument."
              exit 1
            fi

            echo "Deploying ${clusterName}-$MEMBER to $IP..."
            nixos-rebuild switch \
              --flake ".#${clusterName}-$MEMBER" \
              --target-host "root@$IP"
          '';
        };
    };

    # gen-config (task 03): SSH-discover a node and emit a member module.
    gen-config = {
      description = "Discover a node over SSH and emit a member module";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-gen-config";
          runtimeInputs = with pkgs; [ openssh coreutils ];
          text = ''
            set -euo pipefail

            IP=""
            NAME=""
            SSH_USER="root"
            while [[ $# -gt 0 ]]; do
              case "$1" in
                --name) NAME="''${2:-}"; shift 2 ;;
                --ssh-user) SSH_USER="''${2:-}"; shift 2 ;;
                --*) echo "Unknown flag: $1" >&2; exit 1 ;;
                *)
                  if [[ -z "$IP" ]]; then IP="$1"; shift;
                  else echo "Unexpected argument: $1" >&2; exit 1; fi
                  ;;
              esac
            done

            if [[ -z "$IP" ]]; then
              echo "Usage: nixclusterctl ${clusterName} gen-config <ip> [--name <node-name>] [--ssh-user <user>]" >&2
              exit 1
            fi

            echo "Discovering node at $IP (user $SSH_USER)..." >&2

            # Bootstrap TOFU: accept-new pins on first contact, never disables checking (B3).
            SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)

            REMOTE_HOSTNAME=$(ssh "''${SSH_OPTS[@]}" "$SSH_USER@$IP" 'hostname' | tr -d "\r" | head -n1)

            # Pick the whole disk backing /, else the first disk. Reads the real
            # device from the node (e.g. /dev/vda on Colima), never hardcoded.
            DISK=$(ssh "''${SSH_OPTS[@]}" "$SSH_USER@$IP" 'set -e; root_src=$(findmnt -n -o SOURCE / 2>/dev/null || true); pk=""; if [ -n "$root_src" ]; then pk=$(lsblk -no PKNAME "$root_src" 2>/dev/null | head -n1); fi; if [ -n "$pk" ]; then echo "/dev/$pk"; else d=$(lsblk -dn -o NAME,TYPE | grep "disk$" | head -n1 | sed "s/[[:space:]].*//"); echo "/dev/$d"; fi' | tr -d "\r" | head -n1)

            NODE_NAME="''${NAME:-$REMOTE_HOSTNAME}"

            echo "  hostname: $REMOTE_HOSTNAME" >&2
            echo "  disk:     $DISK" >&2
            echo "  member:   $NODE_NAME" >&2

            printf '%s\n' \
              "# Generated by: nixclusterctl ${clusterName} gen-config $IP" \
              "# Save into modules/nodes/$NODE_NAME.nix" \
              "{ ... }:" \
              "{" \
              "  nixcluster.${clusterName}.members.$NODE_NAME = {" \
              "    # nixosConfiguration = ...;  # set your base NixOS config" \
              "    install.ip = \"$IP\";" \
              "    install.disk = \"$DISK\";" \
              "  };" \
              "}"
          '';
        };
    };

    # install (task 04): first-time provisioning via nixos-anywhere.
    install = {
      description = "Install a member via nixos-anywhere";
      builder = { pkgs, cluster, ... }:
        pkgs.writeShellApplication {
          name = "nixclusterctl-${clusterName}-install";
          runtimeInputs = with pkgs; [ nixos-anywhere openssh coreutils ];
          text = ''
            set -euo pipefail

            MEMBER=""
            IP=""
            AGE_KEY_FILE=""
            EXTRA_FILES=""
            while [[ $# -gt 0 ]]; do
              case "$1" in
                --age-key-file) AGE_KEY_FILE="''${2:-}"; shift 2 ;;
                --extra-files) EXTRA_FILES="''${2:-}"; shift 2 ;;
                --*) echo "Unknown flag: $1" >&2; exit 1 ;;
                *)
                  if [[ -z "$MEMBER" ]]; then MEMBER="$1";
                  elif [[ -z "$IP" ]]; then IP="$1";
                  else echo "Unexpected argument: $1" >&2; exit 1; fi
                  shift
                  ;;
              esac
            done

            if [[ -z "$MEMBER" ]]; then
              echo "Usage: nixclusterctl ${clusterName} install <member> [ip] [--age-key-file <path>] [--extra-files <dir>]" >&2
              echo "Members: ${lib.concatStringsSep ", " memberNames}" >&2
              exit 1
            fi

            # Default IP from member config.
            case "$MEMBER" in
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: member: ''
                ${name}) IP="''${IP:-${member.install.ip or ""}}" ;;
              '') cluster.members)}
            esac

            if [[ -z "$IP" ]]; then
              echo "Error: no IP for $MEMBER (set members.$MEMBER.install.ip or pass as arg)" >&2
              exit 1
            fi

            STAGED=""
            cleanup() { [[ -n "$STAGED" ]] && rm -rf "$STAGED"; }
            trap cleanup EXIT

            EF_ARGS=()
            if [[ -n "$AGE_KEY_FILE" ]]; then
              # I3: deliver the age private key into the node's real filesystem at
              # /etc/age/key.txt (mode 0600), outside the nix store/closure. sops-nix
              # reads it on activation (sops.ageKeyFileOnHost), never via the store.
              STAGED=$(mktemp -d)
              install -m 600 -D "$AGE_KEY_FILE" "$STAGED/etc/age/key.txt"
              EF_ARGS+=(--extra-files "$STAGED")
            elif [[ -n "$EXTRA_FILES" ]]; then
              EF_ARGS+=(--extra-files "$EXTRA_FILES")
            fi

            echo "Installing ${clusterName}-$MEMBER on $IP via nixos-anywhere..." >&2
            nixos-anywhere \
              --flake ".#${clusterName}-$MEMBER" \
              --target-host "root@$IP" \
              "''${EF_ARGS[@]}"

            # B3: pin the node host key for subsequent runtime ssh (no accept-new later).
            KH_DIR="./.nixcluster/known_hosts"
            mkdir -p "$KH_DIR"
            ssh-keyscan -H "$IP" >> "$KH_DIR/${clusterName}" 2>/dev/null || true
            echo "Pinned host key for $IP in $KH_DIR/${clusterName}" >&2
          '';
        };
    };
  };

  # Top-level commands = base + any contributed via cluster.commands (attrsOf).
  topCommands = lib.mapAttrs (cmdName: cmdDef: {
    inherit (cmdDef) description;
    package = cmdDef.builder { inherit pkgs lib cluster helpers; };
  }) (baseCommands // (cluster.commands or {}));

  # Namespaced groups, each with built action packages.
  groups = lib.mapAttrs (groupName: groupDef: {
    inherit (groupDef) description;
    actions = lib.mapAttrs (actionName: actionDef: {
      inherit (actionDef) description;
      package = actionDef.builder { inherit pkgs lib cluster helpers; };
    }) groupDef.actions;
  }) (cluster.commandGroups or {});

  # --- help text -------------------------------------------------------------
  topHelp = lib.concatStringsSep "\n"
    (lib.mapAttrsToList (n: c: "  ${n} - ${c.description}") topCommands);

  groupHelp = lib.concatStringsSep "\n" (lib.mapAttrsToList (gName: g:
    let actions = lib.concatStringsSep ", " (lib.attrNames g.actions);
    in "  ${gName} - ${g.description} (${actions})"
  ) groups);

  # --- router cases ----------------------------------------------------------
  topCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (name: cmd: ''
    ${name})
      shift
      exec ${lib.getExe cmd.package} "$@"
      ;;
  '') topCommands);

  groupCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (gName: g:
    let
      actionCases = lib.concatStringsSep "\n" (lib.mapAttrsToList (aName: a: ''
        ${aName})
          shift
          exec ${lib.getExe a.package} "$@"
          ;;
      '') g.actions);
      actionList = lib.concatStringsSep ", " (lib.attrNames g.actions);
    in ''
    ${gName})
      shift
      ACTION="''${1:-}"
      case "$ACTION" in
      ${actionCases}
        help|--help|-h|"")
          echo "${gName} - ${g.description}"
          echo "Actions: ${actionList}"
          ;;
        *) echo "Unknown ${gName} action: $ACTION"; echo "Actions: ${actionList}"; exit 1 ;;
      esac
      ;;
  '') groups);

in
pkgs.writeShellApplication {
  name = "nixclusterctl-${clusterName}";
  text = ''
    show_help() {
      cat << 'EOF'
    nixclusterctl ${clusterName}

    Commands:
    ${topHelp}

    Command groups:
    ${groupHelp}

    Members: ${lib.concatStringsSep ", " memberNames}
    EOF
    }

    CMD="''${1:-}"
    case "$CMD" in
    ${topCases}
    ${groupCases}
      help|--help|-h|"") show_help ;;
      *) echo "Unknown: $CMD"; show_help; exit 1 ;;
    esac
  '';
}
