# nix8sctl <cluster> gen-secrets [--force]
# Generates all secrets for a cluster: age keypair, k3s tokens, SSH keypair
{ pkgs, lib, cluster, clusterName }:

let
  genToken = ''
    head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48
  '';
in
pkgs.writeShellApplication {
  name = "nix8sctl-${clusterName}-gen-secrets";
  runtimeInputs = with pkgs; [ coreutils openssh age sops yq-go ];
  text = ''
    set -euo pipefail

    FORCE="''${1:-}"

    SECRETS_DIR="nix8s/secrets"
    mkdir -p "$SECRETS_DIR"

    AGE_KEY_FILE="$SECRETS_DIR/${clusterName}.age.key"
    AGE_PUB_FILE="$SECRETS_DIR/${clusterName}.age.pub"
    SECRETS_FILE="$SECRETS_DIR/${clusterName}.yaml"
    SSH_KEY_FILE="$SECRETS_DIR/${clusterName}_ssh"
    SSH_PUB_FILE="$SECRETS_DIR/${clusterName}_ssh.pub"
    SOPS_CONFIG="$SECRETS_DIR/.sops.yaml"

    # Check for existing files
    if [[ -f "$AGE_KEY_FILE" && "$FORCE" != "--force" ]]; then
      echo "Warning: Secrets already exist for cluster '${clusterName}'!"
      echo "Files: $AGE_KEY_FILE, $SECRETS_FILE, $SSH_KEY_FILE"
      read -r -p "Overwrite all? [y/N] " response
      if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
      fi
    fi

    echo "Generating secrets for cluster '${clusterName}'..."
    echo ""

    # 1. Generate age keypair
    echo "[1/6] Generating age keypair..."
    rm -f "$AGE_KEY_FILE" "$AGE_PUB_FILE"
    age-keygen 2>&1 | tee "$AGE_KEY_FILE.tmp"
    grep "AGE-SECRET-KEY-" "$AGE_KEY_FILE.tmp" > "$AGE_KEY_FILE"
    grep "public key:" "$AGE_KEY_FILE.tmp" | cut -d: -f2 | tr -d ' ' > "$AGE_PUB_FILE"
    rm "$AGE_KEY_FILE.tmp"
    chmod 600 "$AGE_KEY_FILE"
    AGE_PUB_KEY=$(cat "$AGE_PUB_FILE")
    echo "       Age public key: $AGE_PUB_KEY"

    # 2. Generate SSH keypair
    echo "[2/6] Generating SSH keypair..."
    rm -f "$SSH_KEY_FILE" "$SSH_PUB_FILE"
    ssh-keygen -t ed25519 -f "$SSH_KEY_FILE" -N "" -C "nix8s-${clusterName}" -q
    chmod 600 "$SSH_KEY_FILE"
    SSH_PUB_KEY=$(cat "$SSH_PUB_FILE")
    echo "       SSH public key: ''${SSH_PUB_KEY:0:50}..."

    # 3. Generate k3s tokens
    echo "[3/6] Generating k3s tokens..."
    TOKEN=$(${genToken})
    AGENT_TOKEN=$(${genToken})
    echo "       Generated 2 tokens"

    # 4. Create/update .sops.yaml configuration
    echo "[4/6] Updating .sops.yaml..."
    cat > "$SOPS_CONFIG" << EOF
# SOPS configuration for nix8s secrets
# Auto-generated by: nix8sctl ${clusterName} gen-secrets

keys:
  - &${clusterName} $AGE_PUB_KEY

creation_rules:
  - path_regex: ${clusterName}\\.yaml$
    key_groups:
      - age:
          - *${clusterName}
EOF

    # 5. Create plaintext secrets YAML
    echo "[5/6] Creating secrets file..."
    PLAIN_FILE=$(mktemp)
    cat > "$PLAIN_FILE" << EOF
# Cluster secrets for ${clusterName}
# Encrypted with sops - edit with: nix8sctl ${clusterName} edit-secrets

k3s:
  token: $TOKEN
  agentToken: $AGENT_TOKEN

ssh:
  pubKey: "$SSH_PUB_KEY"
EOF

    # 6. Encrypt with sops
    echo "[6/6] Encrypting secrets with sops..."
    export SOPS_AGE_KEY_FILE="$AGE_KEY_FILE"
    sops --config "$SOPS_CONFIG" --encrypt "$PLAIN_FILE" > "$SECRETS_FILE"
    rm "$PLAIN_FILE"

    echo ""
    echo "=========================================="
    echo "Secrets generated successfully!"
    echo "=========================================="
    echo ""
    echo "Created files:"
    echo "  $AGE_KEY_FILE     - age private key (NEVER COMMIT)"
    echo "  $AGE_PUB_FILE     - age public key"
    echo "  $SECRETS_FILE         - encrypted secrets (safe to commit)"
    echo "  $SSH_KEY_FILE         - SSH private key (NEVER COMMIT)"
    echo "  $SSH_PUB_FILE     - SSH public key"
    echo "  $SOPS_CONFIG          - sops configuration"
    echo ""
    echo "Next steps:"
    echo "  1. Commit encrypted secrets and public keys:"
    echo "     git add $AGE_PUB_FILE $SECRETS_FILE $SSH_PUB_FILE $SOPS_CONFIG"
    echo ""
    echo "  2. Apply configuration to nodes:"
    echo "     nix8sctl ${clusterName} apply <member>"
    echo ""
    echo "  3. Connect to nodes manually:"
    echo "     ssh -i $SSH_KEY_FILE root@<node-ip>"
  '';
}
