#ENC[AES256_GCM,data:TPSMuJcZJCtvvGCRSeH6Fblns0RNLAOf,iv:63Siyrllso9H0hs+7N46F12lVexfQshI8HS+2o69xqg=,tag:7pnORaHYeYYN8CJ2CKfYSg==,type:comment]
#ENC[AES256_GCM,data:uOSS3t9b5BntkikfzSlKxwiPaZuWp3aUrlchXUE7Bd8Xf6r6cA==,iv:q0CPa5Iu9dT5ktGw4tTPOGZjaBOilWQQDJA0ufXDFho=,tag:kQuUhHvIFqFaFyO1GZAXjA==,type:comment]
k3s:
    token: ENC[AES256_GCM,data:dMtx+TjpsjSZszNotAT3hNAwDWdaDgQvcgyOz66n8F9OE69O6hwpdbGC,iv:Zvn8/mJoOEfpx9AAgXhAgz7m6tlYpfdri5JZqwmaBco=,tag:2goRtn+mKqWiimGxhBHjiQ==,type:str]
    agentToken: ENC[AES256_GCM,data:3fGT3/RLAsCRNrWDwS8cq73LwkBbToDMcoI7PCik6uGaqxtTyEBlnNeq,iv:3LhO45gfylTXtDbpveY7+JDwdqLLOwLBS9sepfL5uNY=,tag:ufp4j4yfIjMbwa+0VnX9oA==,type:str]
sops:
    age:
        - recipient: age1mjcjreyetkyy7dg4qynwk7cenryejhqj532scs7quwh69a826cgqyytelk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQVdwRzNOam44Zit2bGNZ
            TkZZVFNodW5ISnRoNm95V1oweTlPT2V3V1VJCjFXYWtmNTE3WmIzcUNiZ1AwdlNo
            dlNaVkw5WnNxN05CTW5NenM0aTRmbjQKLS0tIENJRTNyUG41a2cvSllZUDQyZnZU
            OEJVRG03dHVqL0ZaWFdodGVDdGU3SVkKD7OJlrHpfr+MOAjDlPbb055eHPzo6hsK
            7h+r/C4p7MqKwZ2LIHMMdKBf3uIoz7Zt8rlFlBySD3YVlB+yfi31NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T20:28:36Z"
    mac: ENC[AES256_GCM,data:KfgAULIhsiBwft8exK1CfRrtJU313MkS0CmkFSbKAI00prihuIOReg5tVVvD3eEmCx3DILjFEgw7n9Hk7hgcSdJ6yxlK7NLfRGkgCVrY1y/sL4vUeLpeHNbX1Bb1ntWV2jQoEiWfLFzOoTogyjI0tld1ePRTglPlHB5cR34Hydo=,iv:Qp06w8Se+AcuFVf+qijIqBQiwDCm0/70aCP8JavIHrc=,tag:/MpYzYbm9JUARBaZs/tOzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
