#ENC[AES256_GCM,data:pmsRAlfWI1+jF2Et1B/T4Wz5+cqLAMPu,iv:qpUqtMs/eYrWYFMhoXA1MoyFZL/NaIQlRJTI/Q+d988=,tag:CowZ0tyZj2WZYNWXKnbjsw==,type:comment]
#ENC[AES256_GCM,data:Qw800tVD1D42Od6N4yFnDqdpGrL5JRKPRAiSu/6O9SCMeTbtbg==,iv:A1XMV00EJEQKUGktRppajH/dOlwAL/U0uB0rS4eHJ7A=,tag:Be9N1Ns6cqTkPN928jB8Bg==,type:comment]
k3s:
    token: ENC[AES256_GCM,data:FbpR2xPs5roViJz0M+mX8eBniC+twiJRNvnKixOGTHInr7Z76YkQMw==,iv:zuC6XghZqxIEKt4a4iNLPhl7N6EvVWU1GkpP27jCdUE=,tag:h6uZIqe04/87ptA3iY0KiQ==,type:str]
    agentToken: ENC[AES256_GCM,data:BCY9V1BzMorUQ4dpgLKY4/TzvkXsfCOp9S/HDVEMl8EcsR1udE8BnAqW,iv:NMyZIJKQoYx9dLmvtT19+JUy2Snbu79recno1Gf/bR4=,tag:x9J+A50DFYdpPfEV1CpzYA==,type:str]
ssh:
    publicKey: ENC[AES256_GCM,data:9v3gG+A5257HdEJ+kbufP4vj82XI9XX+nK6u5YmTvP5FclQIuHOGwM7cjWXH+6wHForIZqwhrILI9Ct8Wu9ZXFYHnyVzVxr2lD5g0vHVtfiqXzxAcd5y6Uoi,iv:X5KDr+fatZisQPsaEfB2b+RYQcPSaiJrfmOBiKNteAs=,tag:HF3Ur73Dgd3BmiRzi7wo8Q==,type:str]
sops:
    age:
        - recipient: age18xssndc5ugg27ruqdyjd0dfrgvut6hhg22u0ctj440kn67cuw50sarhm4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QkFqbkJqc2U2OHQzZkVE
            N2s0bXpvZ3pKcDRrdE1laFdWM09oNEV0WlRVClRXUG1MUXlZZkZnUE1RMmM4d3Uy
            NFNDenFwNktSMmNQUGJpaElFcHQrNjgKLS0tIC82YXh5UkVaWTNDOGRXWC9BbVBN
            R1VWU3B0Vk90UGdpNDI3UnloSjNBRVEKnBsA7pM+0s2NrgH7f/5dZBkeA3zMyJov
            vD19EAy4FBkrRMwSQ7bEmM//GItbLbQE4TYxWrp6ktq6YlhLyHYUxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T20:31:28Z"
    mac: ENC[AES256_GCM,data:M4h+5k/6njy/lS6kEVlFOZKBHWhu9+wA3E/IODKkxdfxGTFzdND54Y9i8x07aLZpVTQ6uHMW9P7dAueAS9OCyV9gw45tuhCdTRjeLaGPH2uaCzV2TumEtYGZKeD2vxgY34ZCwbq6i9Xz7PEzmhOIu1ukjfutGKopfy1mFEcP4/A=,iv:wi2W47vzPMxGBaBqwLJpTHbOwNt06iwT3mDAtOQnYaQ=,tag:KR4Jp9LIQlaIdMpC1efxsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
